source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "sprockets-rails", '~> 3.5'
gem "sqlite3", '~> 2.9.5'
gem "puma", "~> 8.0.2"

if ENV['AGENT_TYPE'] == 'apm-otlp-on'
  gem 'solarwinds_apm', '7.1.1'
else
  gem 'solarwinds_apm', '6.1.2'
end
