source "https://rubygems.org"

gem "rails", "~> 7.2.2"
gem "sprockets-rails", '~> 3.5'
gem "sqlite3", '~> 2.9.5'
gem "puma", "~> 8.0.2"

if ENV['AGENT_TYPE'] == 'apm-otlp-on'
  gem 'solarwinds_apm', '7.1.1'
elsif ENV['AGENT_TYPE'] == 'old-on'
  gem 'solarwinds_apm', '7.1.1'
elsif ENV['AGENT_TYPE'] == 'new-on'
  source 'https://rubygems.pkg.github.com/xuan-cao-swi' do
    gem 'solarwinds_apm', '7.0.1.prev2'
  end
else
  gem 'solarwinds_apm', '6.1.2'
end
